name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    name: Test Build and Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Init Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: |
          poetry run pytest
      - name: Build
        run:  poetry run python setup.py sdist bdist_wheel
      - name: Set version in env
        run: echo "TAG_VERSION=`poetry run python setup.py --version`" >> $GITHUB_ENV
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{env.TAG_VERSION}}"
          message: "Latest release"
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          skip_existing: true
