name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    name: Test Build and Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Init Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r common/requirements.txt
          pip install -r tests/test_requirements.txt
          pip install twine pytest
      - name: Test with pytest
        run: |
          pytest
      