name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-publish:
    name: Test Build and Publish
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Init Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: |
          pytest
